### ISSUE TITLE
Trainwrecks Combat knife can't show in the page.

### ISSUE THREAD

**Issue by AwesomeSky** [TcNobo/TcNo-Rust-Drop-Assistant#1]
![image](https://user-images.githubusercontent.com/28689540/126068019-25f8f014-8b04-4fb7-9ae0-cce69d722d60.png)
![image](https://user-images.githubusercontent.com/28689540/126068038-76026868-d7dc-4da3-a07b-75af7caa58e1.png)
I tried to reinstall the extension. But it didn't work during these two days.

**Comment by TCNOco** [comment]
Yes, simple issue...
The Twitch.tv page lists the streamer's name as `Trainwrecks` while Facepunch lists it as `Trainwreckstv`.
I Will get it to check if the name starts with or ends with a username, rather than matches exactly. Should be good enough for situations like these.

**Comment by AwesomeSky** [comment]
Thanks for the help!

**Comment by TCNOco** [comment]
Fix implemented in https://github.com/TcNobo/TcNo-Rust-Drop-Assistant/commit/2883723fdd2e2f374de4152840fdb2ae3b3ac127
Update to addon should be live whenever each platform accepts changes.
